version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
before_build:
- cmd: nuget restore src\Cogworks.ExamineFileIndexer.sln
build:
  project: src/Cogworks.ExamineFileIndexer.sln
  verbosity: minimal