version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
deploy:
  provider: NuGet
  api_key:
    secure: YTgjd2281nKqgxIEe2xIPDwKEMLRkXSc/rJdaJEcjP+WN9jEm91+bPbSeGh+qbfz
  skip_symbols: false
  artifact: /.*\.nupkg/
branches:
  only:
  - master
skip_non_tags: true
before_build:
- cmd: nuget restore src\Cogworks.ExamineFileIndexer.sln
build:
  project: src/Cogworks.ExamineFileIndexer.sln
  verbosity: minimal